<?php

return [
    // ================= web menu =================
    'main' => [
        'M1' => [
            'name' => '학회소개',
            'route' => 'intro.greeting',
            'param' => [],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'M2' => [
            'name' => '학술대회',
            'route' => 'event.domestic',
            'param' => [],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'M3' => [
            'name' => '학술지 및 간행물',
            'route' => 'publication.korean',
            'param' => ['tab'=>1],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'M4' => [
            'name' => '회원관련',
            'route' => 'joinInfo',
            'param' => [],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'M5' => [
            'name' => '저널검색',
            'route' => 'journal.integrationSearch',
            'param' => [],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'M6' => [
            'name' => '학회소식',
            'route' => 'board',
            'param' => ['code'=>'notice'],
            'url' => null,
            'dev' => false,
            'continue' => false,
            'blank'=>false,
        ],
        'MYPAGE' => [
            'name' => '마이페이지',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => true,
            'blank'=>false,
        ],
    ],

    'sub' => [
        'M1' => [ // 학회소개
            'S1' => [
                'name' => '학회장 인사말',
                'route' => 'intro.greeting',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '설립목적',
                'route' => 'intro.goal',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S3' => [
                'name' => 'CI 소개',
                'route' => 'intro.ci',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S4' => [
                'name' => '연혁',
                'route' => 'intro.history',
                'param' => ['tab'=>1],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S5' => [
                'name' => '임원진',
                'route' => 'intro.executive',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S6' => [
                'name' => '정관',
                'route' => 'intro.incorp',
                'param' => ['tab'=>1],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S7' => [
                'name' => '사무국 안내',
                'route' => 'intro.introduce',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'M2' => [ // 학술대회
            'S1' => [
                'name' => '국내 학술대회',
                'route' => 'event.domestic',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '전문가그룹 학술대회',
                'route' => 'event.specialist',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'M3' => [ // 학술지 및 간행물
            'S1' => [
                'name' => '국문지',
                'route' => 'publication.korean',
                'param' => ['tab'=>1],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '영문지',
                'route' => null,
                'param' => [],
                'url' => 'https://www.eeer.org/',
                'continue' => false,
                'blank'=>true,
            ],
            'S3' => [
                'name' => '인터넷 월간지',
                'route' => 'board',
                'param' => ['code'=>'monthly-magazine'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'M4' => [ // 회원관련
            'S1' => [
                'name' => '회원가입 안내',
                'route' => 'joinInfo',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '로그인',
                'route' => 'login',
                'param' => [],
                'url' => null,
                'continue' => true,
                'blank'=>false,
            ],
            'S3' => [
                'name' => '아이디/비밀번호 찾기',
                'route' => 'findId',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
//            'S4' => [
//                'name' => '회비납부 현황조회',
//                'route' => 'main',
//                'param' => [],
//                'url' => null,
//                'continue' => false,
//        'blank'=>false,
//            ],
            'S5' => [
                'name' => '학술대회 참석조회',
                'route' => 'member.attend_check',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
//            'S6' => [
//                'name' => '회원탈퇴',
//                'route' => 'main',
//                'param' => [],
//                'url' => null,
//                'continue' => false,
//        'blank'=>false,
//            ],

            'S8' => [
                'name' => '개인정보 취급 방침',
                'route' => 'member.privacy',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S9' => [
                'name' => '이메일 무단 수집 거부',
                'route' => 'member.email',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'M5' => [ // 저널검색
            'S1' => [
                'name' => '통합검색',
                'route' => 'journal.integrationSearch',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '상세검색',
                'route' => 'journal.detailSearch',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S3' => [
                'name' => '문헌리스트',
                'route' => 'journal.bibList',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'M6' => [ // 학회소식
            'S1' => [
                'name' => '공지사항',
                'route' => 'board',
                'param' => ['code'=>'notice'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '학회 일정 안내',
                'route' => 'board',
                'param' => ['code'=>'event-schedule'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S3' => [
                'name' => '환경관련 행사소식',
                'route' => 'board',
                'param' => ['code'=>'eco'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S4' => [
                'name' => '연간일정',
                'route' => 'board',
                'param' => ['code'=>'annual'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S5' => [
                'name' => '기부금 현황',
                'route' => 'board',
                'param' => ['code'=>'donation'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S6' => [
                'name' => '포토 갤러리',
                'route' => 'board',
                'param' => ['code'=>'photo'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S7' => [
                'name' => '회원동정',
                'route' => 'board',
                'param' => ['code'=>'mems'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S8' => [
                'name' => '구인·구직',
                'route' => 'board',
                'param' => ['code'=>'offer'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
        'MYPAGE' => [ // 마이페이지
            'S1' => [
                'name' => '마이페이지',
                'route' => 'mypage.intro',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S2' => [
                'name' => '개인정보 수정',
                'route' => 'mypage.pwCheck',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S3' => [
                'name' => '비밀번호 수정',
                'route' => 'mypage.password',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S4' => [
                'name' => '회비납부 조회',
                'route' => 'mypage.fee',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S5' => [
                'name' => '학술대회 참석현황',
                'route' => 'mypage.work_attend',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
            'S6' => [
                'name' => '회원탈퇴',
                'route' => 'mypage.withdraw',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
            ],
        ],
    ],
];
